module.exports = {
  TOGGLE_DEVELOPER_TOOLS: 'TOGGLE_DEVELOPER_TOOLS',
  UPDATE_PROJECTION: 'UPDATE_PROJECTION',
  UPDATE_SHADING: 'UPDATE_SHADING',
  UPDATE_PROGRESS: 'UPDATE_PROGRESS',
  INIT_RESPONSE: 'INIT_RESPONSE',
  REFINE_RESPONSE: 'REFINE_RESPONSE',
  RAYCAST: 'RAYCAST',
}
